### ISSUE TITLE
Debug alpha tracking experiments/results

### ISSUE THREAD

**Issue by arnaghosh** [kumarkrishna/fastssl#21]
- [x] Inspect track_alpha branch to understand if code has any bugs
- [x] Ensure that model save/load operation doesn't affect computed eigenspectrum/alpha
- [x] alpha at end of training should be equal to alpha during eval

**Comment by arnaghosh** [comment]
Experiments for Barlowtwins-Cifar10 confirm that alpha after SSL training and just before running linear eval are roughly similar!
- [ ] Fix the dataloader issue in STL10
- [ ] Run (design) hyperparam sweep for Barlowtwins-STL10
- [ ] Run (design) hyperparam sweep for SimCLR-Cifar10
- [ ] Run (design) hyperparam sweep for SimCLR-STL10

**Comment by arnaghosh** [comment]
- [ ] Fix plotting to work with different hparam settings (simclr and barlowtwins)
